// Database types will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_REF > src/lib/supabase/types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          role: string;
          onboarding_completed: boolean;
          subscription_tier: string;
          preferences: Json;
          created_date: string;
          updated_date: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: string;
          onboarding_completed?: boolean;
          subscription_tier?: string;
          preferences?: Json;
          created_date?: string;
          updated_date?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: string;
          onboarding_completed?: boolean;
          subscription_tier?: string;
          preferences?: Json;
          created_date?: string;
          updated_date?: string;
        };
      };
      websites: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          category: string | null;
          slug: string;
          html_content: string;
          css_content: string | null;
          js_content: string | null;
          seo_score: number | null;
          quality_score: number | null;
          key_features: Json | null;
          ai_generation_metadata: Json | null;
          is_published: boolean;
          published_at: string | null;
          preview_url: string | null;
          production_url: string | null;
          custom_domain: string | null;
          created_date: string;
          updated_date: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          category?: string | null;
          slug: string;
          html_content: string;
          css_content?: string | null;
          js_content?: string | null;
          seo_score?: number | null;
          quality_score?: number | null;
          key_features?: Json | null;
          ai_generation_metadata?: Json | null;
          is_published?: boolean;
          published_at?: string | null;
          preview_url?: string | null;
          production_url?: string | null;
          custom_domain?: string | null;
          created_date?: string;
          updated_date?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          category?: string | null;
          slug?: string;
          html_content?: string;
          css_content?: string | null;
          js_content?: string | null;
          seo_score?: number | null;
          quality_score?: number | null;
          key_features?: Json | null;
          ai_generation_metadata?: Json | null;
          is_published?: boolean;
          published_at?: string | null;
          preview_url?: string | null;
          production_url?: string | null;
          custom_domain?: string | null;
          created_date?: string;
          updated_date?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
